/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;

/**
 *
 * @author amaan
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        this.setBackground (new Color (0,0,0,0));       //jframe to transparent background
        this.setLocationRelativeTo(null);   //jframe to center
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        connect2classlogo = new javax.swing.JLabel();
        atadlogo = new javax.swing.JLabel();
        eintvlogo = new javax.swing.JLabel();
        elitelogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpright = new javax.swing.JLabel();
        lblartwork1 = new javax.swing.JLabel();
        lblartwork2 = new javax.swing.JLabel();
        lbl_init = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblwelcome = new javax.swing.JLabel();
        loadingnumber = new javax.swing.JLabel();
        loadingprogress = new javax.swing.JProgressBar();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(728, 484));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(60);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        connect2classlogo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        connect2classlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/c2clogo.png"))); // NOI18N
        connect2classlogo.setText("Connect2Class");
        kGradientPanel1.add(connect2classlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        atadlogo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atadlogo.setForeground(new java.awt.Color(102, 102, 102));
        atadlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atd24px.png"))); // NOI18N
        atadlogo.setText("ATAD Co-Operation   &");
        kGradientPanel1.add(atadlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        eintvlogo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eintvlogo.setForeground(new java.awt.Color(102, 102, 102));
        eintvlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eintv24px.png"))); // NOI18N
        eintvlogo.setText(" Eintv");
        kGradientPanel1.add(eintvlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        elitelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/elite classes ec 120px.png"))); // NOI18N
        elitelogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel1.add(elitelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, -1));
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 270, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setText("Elite Classes");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Designed by :");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        cpright.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cpright.setForeground(new java.awt.Color(102, 102, 102));
        cpright.setText("© 2020 ATAD. All right reserved , Artwork by Aisf & JC.");
        kGradientPanel1.add(cpright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblartwork1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblartwork1.setForeground(new java.awt.Color(102, 102, 102));
        lblartwork1.setText("Elite Classes is a Tution classes from Ist to Xth");
        kGradientPanel1.add(lblartwork1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lblartwork2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblartwork2.setForeground(new java.awt.Color(102, 102, 102));
        lblartwork2.setText("Founded by : AmaanJC ");
        kGradientPanel1.add(lblartwork2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        kGradientPanel1.add(lbl_init, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Initializing");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading.gif"))); // NOI18N
        jLabel1.setOpaque(true);
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("True Guidance Is A Key To Success");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 290, 380));

        lblwelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblwelcome.setText("Welcome To");
        getContentPane().add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 39));

        loadingnumber.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        loadingnumber.setForeground(new java.awt.Color(169, 224, 49));
        loadingnumber.setText("99%");
        getContentPane().add(loadingnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        loadingprogress.setForeground(new java.awt.Color(169, 224, 49));
        loadingprogress.setBorderPainted(false);
        loadingprogress.setFocusable(false);
        loadingprogress.setRequestFocusEnabled(false);
        loadingprogress.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(loadingprogress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 730, 10));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve final.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        setBounds(0, 0, 730, 488);
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atadlogo;
    private javax.swing.JLabel background;
    private javax.swing.JLabel connect2classlogo;
    private javax.swing.JLabel cpright;
    private javax.swing.JLabel eintvlogo;
    private javax.swing.JLabel elitelogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_init;
    private javax.swing.JLabel lblartwork1;
    private javax.swing.JLabel lblartwork2;
    private javax.swing.JLabel lblwelcome;
    public javax.swing.JLabel loadingnumber;
    public javax.swing.JProgressBar loadingprogress;
    // End of variables declaration//GEN-END:variables
}
